[versions]
agp = "8.13.2"
kotlin = "2.3.0"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.1"
composeBom = "2024.09.00"
hilt = "2.57.1"
ksp = "2.2.20-2.0.3"
retrofit = "3.0.0"
okhttp = "5.3.0"
room = "2.8.4"
moshiVersion = "1.15.2"
ktlint = "14.0.1"
coil = "3.3.0"
mockito = "5.21.0"
mockk = "1.14.7"
coroutineTest = "1.10.2"
turbine = "1.2.1"
navigationCompose = "2.9.6"
numberPicker = "1.0.5"
hiltNavigation = "1.2.0"
material = "1.13.0"
firebase = "34.8.0"
firebasePlugin = "3.0.6"
googleServices ="4.4.4"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-navigation = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigation" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofitMoshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit" }
number-picker = { group = "com.chargemap.compose", name = "numberpicker", version.ref = "numberPicker" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttpLogging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }

roomDB = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
roomCompiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
roomKTX = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
roomTest = { group = "androidx.room", name = "room-testing", version.ref = "room" }

moshi = { group = "com.squareup.moshi", name = "moshi", version.ref = "moshiVersion" }
moshiKotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshiVersion" }

coil = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coilNetwork = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil" }
mockito = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
mockitoKTX = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockito" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
coroutineTest = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutineTest" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase" }
firebase-crashLatics = { group = "com.google.firebase", name = "firebase-crashlytics" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
frieBase = { id = "com.google.firebase.crashlytics", version.ref="firebasePlugin"}
google-services = {id ="com.google.gms.google-services", version.ref="googleServices"}